env:
  es6: true
  node: true
  mocha: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends: 'eslint:recommended'

rules:
  spaced-comment: 2
  callback-return: 2
  space-infix-ops: 2
  newline-after-var: 2
  handle-callback-err: 2
  newline-before-return: 2
  semi: [2, 'always']
  max-statements: [2, 30]
  comma-dangle: [2, never]
  indent: [2, 2, {'SwitchCase': 1}]
  quotes: [2, 'single', {'allowTemplateLiterals': true}]
