language: node_js
node_js:
  - "7"
  - "6"
before_script:
  - cp chill.yml.dist chill.yml
script:
  - yarn test:coverage
after_script:
  - yarn codecov
notifications:
  hipchat: edf5ec8197d2496883113ea2d6449a@3743872
